import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, Droplets, ShieldCheck, Waves, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export default function PublicHome() {
  const { isAuthenticated, user, logout } = useAuth();
  const [showPrompt, setShowPrompt] = useState(false);
  const location = useLocation();
  const privateDestination = '/private-dashboard';
  const handleLogout = async () => {
    try {
      await logout();
    } catch {
      // Local authentication state is still cleared by AuthProvider.
    }
  };

  return <main className="min-h-screen bg-navy-950 text-slate-200">
    <header className="sticky top-0 z-20 border-b border-white/5 bg-navy-950/85 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><Link to="/" className="flex items-center gap-2 font-bold text-white"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-cyan-400 to-blue-500"><Waves className="h-5 w-5" /></span>AquaSentinel AI</Link><div className="hidden items-center gap-5 text-sm text-slate-400 md:flex"><Link to="/features" className="hover:text-cyan-300">Features</Link><Link to="/about" className="hover:text-cyan-300">About</Link><Link to="/how-it-works" className="hover:text-cyan-300">How It Works</Link><Link to="/contact" className="hover:text-cyan-300">Contact</Link></div><div className="flex items-center gap-3 text-sm">{isAuthenticated ? <><span className="hidden text-slate-400 sm:block">{user?.name}</span><Link to={privateDestination} className="text-cyan-400 hover:text-cyan-300">Dashboard</Link><button onClick={() => void handleLogout()} className="text-slate-400 hover:text-white">Logout</button></> : <><Link to="/login" className="text-slate-300 hover:text-white">Login</Link><Link to="/register" className="rounded-lg bg-cyan-500 px-3 py-2 font-medium text-navy-950 hover:bg-cyan-400">Register</Link></>}</div></nav></header>
    <section className="mx-auto max-w-6xl px-4 py-20 text-center sm:px-6"><div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><Droplets className="h-7 w-7" /></div><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Intelligent water monitoring</p><h1 className="mx-auto max-w-3xl text-4xl font-bold tracking-tight text-white sm:text-6xl">See water quality risks before they become emergencies.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-400">AquaSentinel AI brings sensor analytics, anomaly detection, and early-warning intelligence into one clear monitoring platform.</p><div className="mt-9 flex justify-center gap-3"><Link to="/features" className="rounded-lg border border-cyan-400/30 px-5 py-3 text-sm font-medium text-cyan-300 hover:bg-cyan-400/10">Explore features</Link>{isAuthenticated ? <Link to={privateDestination} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-3 text-sm font-semibold text-white">Open dashboard<ArrowRight className="h-4 w-4" /></Link> : <button onClick={() => setShowPrompt(true)} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-3 text-sm font-semibold text-white">Access private monitoring<ArrowRight className="h-4 w-4" /></button>}</div></section>
    <section className="mx-auto grid max-w-6xl gap-4 px-4 pb-20 sm:grid-cols-3 sm:px-6">{[{ icon: Waves, title: 'Water quality', body: 'Understand vital sensor parameters at a glance.' }, { icon: ShieldCheck, title: 'Early warnings', body: 'Identify abnormal patterns before they escalate.' }, { icon: Droplets, title: 'AI-assisted analysis', body: 'Bring anomaly and risk signals into context.' }].map(({ icon: Icon, title, body }) => <article className="glass-card p-6" key={title}><Icon className="mb-4 h-5 w-5 text-cyan-400" /><h2 className="font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></article>)}</section>
    {showPrompt && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 px-4" role="dialog" aria-modal="true" aria-labelledby="login-required"><div className="glass-card w-full max-w-sm p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 id="login-required" className="font-semibold text-white">Login required to continue</h2><p className="mt-2 text-sm leading-6 text-slate-400">Please log in or create an account to access private monitoring data.</p></div><button onClick={() => setShowPrompt(false)} aria-label="Close prompt" className="text-slate-400 hover:text-white"><X className="h-5 w-5" /></button></div><div className="mt-6 flex gap-3"><Link to="/login" state={{ from: { pathname: privateDestination, search: location.search } }} className="auth-submit">Login</Link><Link to="/register" state={{ from: { pathname: privateDestination } }} className="flex w-full items-center justify-center rounded-lg border border-cyan-400/30 px-4 text-sm font-medium text-cyan-300 hover:bg-cyan-400/10">Create Account</Link></div></div></div>}
  </main>;
}
